### ISSUE TITLE
An error during setup, while running "react-native link" and "react-native run-android"

### ISSUE THREAD

**Issue by rahamin1** [GeekyAnts/NativeBase-KitchenSink#133]
### Steps to Reproduce
1. git clone git@github.com:GeekyAnts/NativeBase-KitchenSink.git
2.  cd NativeBase-KitchenSink
3. yarn
4. react-native link react-native-vector-icons

### My environment
Windows 10

### Expected Behavior
No errors...

### Actual Behavior
What actually happens?
```
# react-native link react-native-vector-icons
node_modules\react-native\local-cli\cliEntry.js:30
import type {CommandT} from './commands';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (C:\esites-native\native-base\NativeBase-KitchenSink\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (C:\esites-native\native-base\NativeBase-KitchenSink\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**Comment by dzxxdzy** [comment]
try replacing  the  react native version with 0.55.4

**Comment by fonderco** [comment]
I'm sorry, I'm new to React Native, how do I do that?

**Comment by rahamin1** [comment]
@dzxxdzy advice worked!

@fonderco 

- Edit `package.json`, and change the react-native version to 0.55.4.
- Delete the `node_modules` folder 
- run `yarn`
- then install and run on your device (on android: `react-native run-android`)
