### ISSUE TITLE
Expected "/*" but "0" found

### ISSUE THREAD

**Issue by anasred** [GeekyAnts/NativeBase-KitchenSink#140]
when I did the last step 
react-native link react-native-vector-icons
I got this:

rnpm-install ERR! Something went wrong while linking. Error: Expected "/*" but "0" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 

Expected "/*" but "0" found.

SyntaxError: Expected "/*" but "0" found.
    at peg$buildStructuredError (/Users/anasahmar/Downloads/NativeBase-KitchenSink-master/node_modules/xcode/lib/parser/pbxproj.js:412:12)
    at Object.peg$parse [as parse] (/Users/anasahmar/Downloads/NativeBase-KitchenSink-master/node_modules/xcode/lib/parser/pbxproj.js:1886:11)
    at pbxProject.parseSync (/Users/anasahmar/Downloads/NativeBase-KitchenSink-master/node_modules/xcode/lib/pbxProject.js:46:24)
    at isInstalled (/Users/anasahmar/Downloads/NativeBase-KitchenSink-master/node_modules/react-native/local-cli/link/ios/isInstalled.js:19:60)
    at Object.isInstalled (/Users/anasahmar/Downloads/NativeBase-KitchenSink-master/node_modules/react-native/local-cli/link/ios/common/isInstalled.js:8:5)
    at Object.keys.forEach.platform (/Users/anasahmar/Downloads/NativeBase-KitchenSink-master/node_modules/react-native/local-cli/link/link.js:57:36)
    at Array.forEach (<anonymous>)
    at linkDependency (/Users/anasahmar/Downloads/NativeBase-KitchenSink-master/node_modules/react-native/local-cli/link/link.js:44:32)
    at <anonymous>

**Comment by gedarius** [comment]
same error here, i tried  a "npm add react-native-vector-icons" and the a lot of other errors blow

**Comment by suvenduchhatoi** [comment]
Check if you are working on the latest version of NBKS
run 'react-native upgrade`
Then run `react-native link react-native-vector-icons` again
It should work

**Comment by SupriyaKalghatgi** [comment]
#147
