### ISSUE TITLE
not running the class from metro loader module

### ISSUE THREAD

**Issue by dharmendrashah** [GeekyAnts/NativeBase-KitchenSink#184]
```
`
C:\Users\hp\Desktop\chatApplicationTest\3\node_modules\metro-config\src\defaults\blacklist.js:34
  return new RegExp(
         ^

SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\Users\hp\Desktop\chatApplicationTest\3\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (C:\Users\hp\Desktop\chatApplicationTest\3\node_modules\react-native\local-cli\util\Config.js:56:10)
    at Object.<anonymous> (C:\Users\hp\Desktop\chatApplicationTest\3\node_modules\react-native\local-cli\util\Config.js:71:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._compile (C:\Users\hp\Desktop\chatApplicationTest\3\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.newLoader [as .js] (C:\Users\hp\Desktop\chatApplicationTest\3\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
`
```

solve this issue its important

**Comment by vinibiso** [comment]
Same problem!
I downloaded the zip instead of cloning.
Don't know if that makes a difference.

edit:
Further testin i believe this is a problem with the paths on Windows specifically.
On mac it worked fine.

**Comment by exlnt** [comment]
I cloned the repo and ran into this same issue! I am running on windows. Is there any solution?

[This helps fix the error](https://stackoverflow.com/a/58122821/8195788l) but the app still does not launch.

**Comment by Moumit** [comment]
With this full replacement on **node_modules\metro-config\src\defaults\blacklist.js** the issue resolved and app is running on VSCode 

```
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */
"use strict";

var path = require("path"); // Don't forget to everything listed here to `package.json`
// modulePathIgnorePatterns.

var sharedBlacklist = [
  /node_modules\/react\/dist\/.*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

function escapeRegExp(pattern) {
  if (Object.prototype.toString.call(pattern) === "[object RegExp]") {
    return pattern.source.replace(/\//g, path.sep);
  } else if (typeof pattern === "string") {
    var escaped = pattern.replace(/[\-\[\]\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&"); // convert the '/' into an escaped local file separator

    return escaped.replace(/\//g, "\\" + path.sep);
  } else {
    throw new Error("Unexpected blacklist pattern: " + pattern);
  }
}

function blacklist(additionalBlacklist) {
  return new RegExp(
    "(" +
      (additionalBlacklist || [])
        .concat(sharedBlacklist)
        .map(escapeRegExp)
        .join("|") +
      ")$"
  );
}

module.exports = blacklist;

```

**Comment by janiez** [comment]
In my case for Windows and Nodejs 12 I required the follow.
* Add this setting into package.json
    {
     ...
     "resolutions": {
         "metro-config": "bluelovers/metro-config-hotfix-0.56.x",
         "graceful-fs": "4.2.4"
      },
    ...
   }
* yarn install
* react-native run-android
