### ISSUE TITLE
Native module CodePushNativeModule tried to override CodePushNativeModule for module name CodePush.

### ISSUE THREAD

**Issue by TheRealJAG** [GeekyAnts/NativeBase-KitchenSink#19]
When I try to run NativeBase in AVD I get the following error at runtime. 

`java.lang.IllegalStateException: Native module CodePushNativeModule tried to override CodePushNativeModule for module name CodePush. If this was your intention, set canOverrideExistingModule=true
                                                                            at com.facebook.react.cxxbridge.NativeModuleRegistry.<init>(NativeModuleRegistry.java:53)
                                                                            at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:894)
                                                                            at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
                                                                            at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
                                                                            at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)`

**Comment by TheRealJAG** [comment]
I am also getting this error in the starter kit. 

I believe the problem stems from this command 

`react-native link`

`C:\Users\Jorge A. Gonzalez\Documents\AndroidDev\native-starter-kit>react-native link
? What is your CodePush deployment key for Android (hit <ENTER> to ignore) ZKaoLPSbHGqy17JWb2TfR2RF3yvXEk4o0bGIG
rnpm-install info Linking react-native-code-push android dependency
rnpm-install info Android module react-native-code-push has been successfully linked
rnpm-install info iOS module react-native-code-push is already linked
"CodePush.h" header already imported.
C:\Users\Jorge A. Gonzalez\Documents\AndroidDev\native-starter-kit\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)\n/)[1];
                                                                                               ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (C:\Users\Jorge A. Gonzalez\Documents\AndroidDev\native-starter-kit\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26:96)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jorge A. Gonzalez\Documents\AndroidDev\native-starter-kit\node_modules\react-native-code-push\scripts\postlink\run.js:1:63)
    at Module._compile (module.js:570:32)
C:\Users\Jorge A. Gonzalez\Documents\AndroidDev\native-starter-kit\node_modules\react-native\local-cli\core\makeCommand.js:19
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (C:/Users/Jorge A. Gonzalez/Documents/AndroidDev/native-starter-kit/node_modules/react-native/local-cli/core/makeCommand.js:19:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

C:\Users\Jorge A. Gonzalez\Documents\AndroidDev\native-starter-kit>`

**Comment by SupriyaKalghatgi** [comment]
@TheRealJAG Could you please share your **MainApplication.java** file here.

**Comment by SupriyaKalghatgi** [comment]
@TheRealJAG 
The error may be because of **CodePush** linked twice.
If yes, edit `MainApplication.java` to remove multiple instances of **CodePush**
And then it should be up and running

**Comment by SupriyaKalghatgi** [comment]
Closing this issue due to inactivity
Please reopen if the issue continues

**Comment by easysoft2k15** [comment]
I'm having the same problem.
Following @SupriyaKalghatgi  suggestion of removing the duplicate _CodePush_ from _MainApplication.java_ everything start working.
But each time I'm issuing a react-native link command, the duplicate lines get pushed again into _MainApplication.java_
Anyone knows why?
I'd like to fix the root problem but I'm not familiar with react-native and I don't know what's causing the problem.
Thanks

**Comment by Kodax9** [comment]
Miss Supriya, can you please let me know which one mainapplication.java should i edit ? in what folder can i find it ?

**Comment by GeekRishabh** [comment]
@Kodax9  you can try the CRNA/Expo version of the app [using](https://github.com/GeekyAnts/NativeBase-KitchenSink/tree/CRNA)

**Comment by SupriyaKalghatgi** [comment]
@Kodax9 Still on it?

**Comment by alainib** [comment]
i got the same error because of "react-native link" 

i edited the file "...native-starter-kit\android\app\src\main\java\com\nativestarterkit\MainApplication.java"

and removed one line ( i get two the same with `new CodePush(null...)`

     protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new CodePush(null, getApplicationContext(), BuildConfig.DEBUG) ,
//  remove this          new CodePush(null, getApplicationContext(), BuildConfig.DEBUG) 
      );
    }

**Comment by SupriyaKalghatgi** [comment]
@alainib Which branch are you on?

**Comment by HossamSamir** [comment]
I was having the same issue, You can simply fix it by:
1. removing multiple instances of CodePush in the `MainApplication.java` like @SupriyaKalghatgi said.
2. removing those duplicates in the same file as shown in the picture.

![untitled](https://user-images.githubusercontent.com/15352675/28263502-dc033128-6a9b-11e7-9abc-a55ad79b7a12.png)

**Comment by voukeng** [comment]
After doing that, this is what i get
![image](https://user-images.githubusercontent.com/25953516/29774477-d1ffa1f2-8c01-11e7-8527-e6d9db017d5c.png)

**Comment by SupriyaKalghatgi** [comment]
@voukeng Can I know what changes did you make?

**Comment by mirq** [comment]
@voukeng  you need to delete build folder contents manually before another try.

**Comment by parisajadidi** [comment]
Please don't sent me any other Email

**Comment by trinadhkoya9** [comment]
not yet closed still experiencing the same
