### ISSUE TITLE
Error while doing 'react-native link'

### ISSUE THREAD

**Issue by Randyanto** [GeekyAnts/NativeBase-KitchenSink#3]
**Error while doing 'react-native link'**

```
rnpm-install info Linking react-native-code-push android dependency
rnpm-install info Android module react-native-code-push has been successfully li
nked
rnpm-install info iOS module react-native-code-push is already linked
"CodePush.h" header already imported.
D:\Users\user\Documents\React\NativeBase-KitchenSink\node_modules\react-native-c
ode-push\scripts\postlink\ios\postlink.js:26
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLoc
ation = .*)\n/)[1];

               ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (D:\Users\user\Documents\React\NativeBase-KitchenSink\
node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26:96)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\user\Documents\React\NativeBase-KitchenSink\
node_modules\react-native-code-push\scripts\postlink\run.js:1:63)
    at Module._compile (module.js:541:32)
 D:\Users\user\Documents\React\NativeBase-KitchenSink\node_modules\react-native\
local-cli\core\makeCommand.js:19
        throw new Error(`Error occured during executing "${ command }" command`)
;
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/
scripts/postlink/run" command
    at ChildProcess.prelink (D:/Users/user/Documents/React/NativeBase-KitchenSin
k/node_modules/react-native/local-cli/core/makeCommand.js:19:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by sankhadeeproy007** [comment]
Did you try running the app anyway?

**Comment by Randyanto** [comment]
![image](https://cloud.githubusercontent.com/assets/1468905/19551908/1f3dfb52-96e0-11e6-97a3-b82d9b907254.png)

**Comment by SupriyaKalghatgi** [comment]
@Randyanto Please check this on React Native CodePush [Issue #539](https://github.com/Microsoft/react-native-code-push/issues/539)

**Comment by Randyanto** [comment]
@SupriyaKalghatgi @sankhadeeproy007 the override error in the Android is happened because I did 'react-native link' several times when I try to solve my first error. That makes the CodePush being imported and initialized several times in MainApplication.java.

You can refer to this issue for the first problem https://github.com/Microsoft/react-native-code-push/issues/477 At the first time I think it's because there are 2 AppDelegate.m in the project but after I console.log it, it already points to the right path. The problem is the jsCodeLocation is null.

**Comment by SupriyaKalghatgi** [comment]
@Randyanto Did you check the latest release of NativeBase Kitchen Sink?

Do you find same issues?

**Comment by Randyanto** [comment]
@SupriyaKalghatgi  sorry, I have not checked it yet, still struggling to learn Redux :)

**Comment by obergshavefun** [comment]
I'm having the same issue both for NSK and KitchenSink.  

`$ react-native link
? What is your CodePush deployment key for Android (hit <ENTER> to ignore) KeyHere....?
rnpm-install info Linking react-native-code-push android dependency
rnpm-install info Android module react-native-code-push has been successfully linked
rnpm-install info iOS module react-native-code-push is already linked
"CodePush.h" header already imported.
C:\Users\User\Source\NativeBase-KitchenSink\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)\n/)[1];
                                                                                               ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (C:\Users\User\Source\NativeBase-KitchenSink\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26:96)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\Source\NativeBase-KitchenSink\node_modules\react-native-code-push\scripts\postlink\run.js:1:63)
    at Module._compile (module.js:556:32)
C:\Users\User\Source\NativeBase-KitchenSink\node_modules\react-native\local-cli\core\makeCommand.js:29
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (C:/Users/User/Source/NativeBase-KitchenSink/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
`
Could you reopen this as an issue?  I'm on react-native 0.38.

**Comment by TheRealJAG** [comment]
I'm getting this same issue after purchasing NativeStarterPro.

**Comment by TheRealJAG** [comment]
@obergshavefun did you ever find a fix for this?

**Comment by SupriyaKalghatgi** [comment]
@obergshavefun That might be due to linking third party modules for multiple times

**Comment by SupriyaKalghatgi** [comment]
@TheRealJAG Are you talking about Native Starter Pro or Native Starter Kit?

**Comment by TheRealJAG** [comment]
@SupriyaKalghatgi Pro.

**Comment by SupriyaKalghatgi** [comment]
@TheRealJAG Did you check [this](https://github.com/GeekyAnts/NativeBase-KitchenSink/issues/3#issuecomment-255289544)?

**Comment by bluedusk** [comment]
I'm getting this same issue, on react native 0.41.0.
