### ISSUE TITLE
Link error on Android

### ISSUE THREAD

**Issue by bluedusk** [GeekyAnts/NativeBase-KitchenSink#30]
Hi guys, I have this issue on windows(node v4.4.4) when finished `npm i` then try to run `react-native link` ,  any idea what's might be the problem ? I ignored the CodePush deployment key because I dont have any.

> ? What is your CodePush deployment key for Android (hit <ENTER> to ignore)
rnpm-install info Linking react-native-code-push android dependency
rnpm-install info Android module react-native-code-push has been successfully linked
rnpm-install info iOS module react-native-code-push is already linked
"CodePush.h" header already imported.
D:\Workspace\React\NativeBase-KitchenSink\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)\n/)[1];
                                                                                     

> TypeError: Cannot read property '1' of null
    at Object.<anonymous> (D:\Workspace\React\NativeBase-KitchenSink\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26:96)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Workspace\React\NativeBase-KitchenSink\node_modules\react-native-code-push\scripts\postlink\run.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by HermantoTang** [comment]
#29
