### ISSUE TITLE
cant run KitchenSink on iOS

### ISSUE THREAD

**Issue by dominicsavb** [GeekyAnts/NativeBase-KitchenSink#50]
I cant run KitchenSink on iOS simulator

My step is:
```
git clone https://github.com/GeekyAnts/NativeBase-KitchenSink.git
cd NativeBase-KitchenSink
npm install
react-native link
react-native run-ios
```

and the error is **DeviceInfo native module is not installed correctly**

how to solve this problem?
Thank you

**Comment by SupriyaKalghatgi** [comment]
This dd'nt happen before to anyone

**Comment by dominicsavb** [comment]
But Happen to me

`Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactDebugCurrentFrame` from `/Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react-native/Libraries/Renderer/src/renderers/shared/fiber/ReactFiberContext.js`: Module does not exist in the module map or in these directories:
  /Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react-native/node_modules/react/lib
,   /Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react/lib
,   /Users/admin/node_modules/react/lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ResolutionRequest._resolveNodeDependency (/Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:394:11)
    at tryResolveSync (/Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:136:20)
    at tryResolveSync (/Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:66:12)
    at ResolutionRequest.resolveDependency (/Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:134:22)
    at dependencyNames.map.name (/Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (/Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:42)
    at Promise.resolve.then (/Users/admin/ReactProject/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:169:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.ios.js`  99.3% (1091/1095), failed.
`


this is my package.json
`"dependencies": {
    "color": "~0.11.1",
    "lodash": "^4.13.1",
    "moment": "^2.13.0",
    "native-base": "2.1.0",
    "react": "^15.5.4",
    "react-native": "^0.44.0",
    "react-native-code-push": "^2.0.3-beta",
    "react-native-easy-grid": "^0.1.8",
    "react-native-modalbox": "^1.3.4",
    "react-native-navigation-redux-helpers": "^0.5.0",
    "react-native-router-flux": "3.39.1",
    "react-native-scrollable-tab-view": "^0.6.0",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-form": "^6.2.0",
    "redux-persist": "^3.2.2",
    "redux-thunk": "^2.1.0",
    "remote-redux-devtools": "^0.3.3",
    "whatwg-fetch": "^2.0.3"
  },`

**Comment by SupriyaKalghatgi** [comment]
@dominicsavb The `package.json` of KitchenSink has
```
"native-base": "2.1.0",
"react-native": "0.42.3"
```

And you are trying to install
```
"native-base": "2.1.0",
"react-native": "^0.44.0"
```

Please check the [Release Notes](https://github.com/GeekyAnts/NativeBase/releases) of NativeBase for dependencies

**Comment by SupriyaKalghatgi** [comment]
Closing this issue due to inactivity
Please reopen if the issue continues
