### ISSUE TITLE
Using latest native-base ~2.1.5 yields build errors 

### ISSUE THREAD

**Issue by vtsatskin** [GeekyAnts/NativeBase-KitchenSink#53]
Running NativeBase-KitchenSink locally on a development machine works properly (as of checking c985e7a2198e788eb1444a464771ffe5905a7f0f). However, I wanted to use this project check my contributions to NativeBase. So I linked the [latest master](https://github.com/GeekyAnts/NativeBase/commit/f630a81f11ec8df2c78cd4dbc87602479bc74afd) of NativeBase:

```
cd NativeBase-KitchenSink
yarn link native-base
react-native run-ios
```

The following error happens:

```
** BUILD FAILED **


The following build commands failed:

    CpResource /Users/vt/Code/NativeBase-KitchenSink/node_modules/native-base/Fonts/Andale\ Mono.ttf build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app/Andale\ Mono.ttf
    CpResource /Users/vt/Code/NativeBase-KitchenSink/node_modules/native-base/Fonts/Arial.ttf build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app/Arial.ttf
    CpResource /Users/vt/Code/NativeBase-KitchenSink/node_modules/native-base/Fonts/Arial\ Black.ttf build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app/Arial\ Black.ttf
    CpResource /Users/vt/Code/NativeBase-KitchenSink/node_modules/native-base/Fonts/Comic\ Sans\ MS.ttf build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app/Comic\ Sans\ MS.ttf
    CpResource /Users/vt/Code/NativeBase-KitchenSink/node_modules/native-base/Fonts/Courier\ New.ttf build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app/Courier\ New.ttf
    (5 failures)
```

This is probably due to the [issues described in upgrading to native-base 2.1.5](https://github.com/GeekyAnts/NativeBase/issues/928).

Running the react native packager yields the following errors:
```
Loading dependency graph...
React packager ready.

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/vt/Code/NativeBase/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/vt/Code/NativeBase-KitchenSink/node_modules/react-native/local-cli/core/__fixtures__/files/package.json
```

Currently this is preventing me from contributing to the main NativeBase project easily.

**Comment by SupriyaKalghatgi** [comment]
@vtsatskin Did you unlink the vector-icons and tried building again?

**Comment by vtsatskin** [comment]
@SupriyaKalghatgi I tried unlinking react-native-vector-icons in the NativeBase-KitchenSink project. The same error still occurs when running the packager

```
➜  NativeBase-KitchenSink git:(master) ✗ react-native unlink react-native-vector-icons
Scanning 755 folders for symlinks in /Users/vt/Code/NativeBase-KitchenSink/node_modules (29ms)
rnpm-install info Android module react-native-vector-icons is not installed 
rnpm-install info iOS module react-native-vector-icons is not installed 
rnpm-install info Unlinking assets from ios project 
rnpm-install info Unlinking assets from android project 
rnpm-install info react-native-vector-icons assets has been successfully unlinked from your project 
```

```
➜  NativeBase-KitchenSink git:(master) ✗ react-native start

...

Loading dependency graph...
React packager ready.

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/vt/Code/NativeBase/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/vt/Code/NativeBase-KitchenSink/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/vt/Code/NativeBase/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/vt/Code/NativeBase-KitchenSink/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/vt/Code/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/vt/Code/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
    at <anonymous>
```

As an experiment, I also tried removing the react-native-vector-icons entirely from the KitchenSink project, this did not fix the issue:

```
➜  NativeBase-KitchenSink git:(master) ✗ rm -rf node_modules/react-native-vector-icons 
```

Unlinking react-native-vector-icons in the native-base project also does not fix the issue:

```
➜  NativeBase git:(master) ✗ react-native unlink react-native-vector-icons
Scanning 693 folders for symlinks in /Users/vt/Code/NativeBase/node_modules (11ms)
rnpm-install info react-native-vector-icons assets has been successfully unlinked from your project 
```

**Comment by SupriyaKalghatgi** [comment]
@vtsatskin Ok i will pull from `master` and run once

**Comment by SupriyaKalghatgi** [comment]
@vtsatskin I pulled KitchenSink from `master`, you need to follow these steps

- uninstall native-base
- install native-base
- Check `node_modules/native-base/Fonts` against `Info.plist` in Xcode and `Copy Bundle Resources` from **Build Phases**
- Remove fonts which are not present in `node_modules/native-base/Fonts`
- This is explained briefly in [#928](https://github.com/GeekyAnts/NativeBase/issues/928) of NativeBase

**Comment by SupriyaKalghatgi** [comment]
@vtsatskin But then you get this error of React Native

 [#851](https://github.com/GeekyAnts/NativeBase/issues/851) of NativeBase
![simulator screen shot jun 20 2017 11 17 07 am](https://user-images.githubusercontent.com/13464885/27318451-0644be54-55aa-11e7-96dd-4062e3effbc6.png)

Click [here](https://github.com/GeekyAnts/NativeBase/issues/851#issuecomment-303354135) for solution

**Comment by SupriyaKalghatgi** [comment]
@vtsatskin Did you try?

**Comment by SupriyaKalghatgi** [comment]
Closing this due to inactivity
Please reopen if the issue continues
